### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by hirounsung** [Necrownyx/Twitch-Account-Toolbox#4]
I think some great features for this tool would be: 

-support for using proxies
-use fake-useragent
-request the oauth for each account created (would require the user to click "accept" when doing so)

This would allow the program to create a larger amount of accounts in one sitting and honestly I am assuming most people using this tool want the oauth for the account so it would make it where they don't have to manually do it on another website or with another tool. I have some python scripts that already use the proxy and fake-useragent so I will see how hard it is to add those myself. I also found a twitch API github page that has the code for requesting oauth.

**Comment by Necrownyx** [comment]
Sorry for the late response,

Proxies are technically supported in the add-proxies branch although i have not got access to any proxies to test it with so it may be non functional,

I haven't heard of fake-useragent before if you could potentially explain its purpose and what it would add to the project that would be appreciated,

I'm going to look into getting the oauth for each account for the meantime there are other projects that can get the oauth of the account by inputting the username:password string generated by the account creator

If you were interested in improving the project feel free to fork the project and improve it for yourself and others.

Nyx,

**Comment by hirounsung** [comment]
Hey, no worries.

There is a library in python called fake-useragent, a user agent is what your browser broadcasts to websites. It tells the website what browser/version is being used, what operating system along with other metrics. Websites can sometimes try to use this with other information to determine if some one is trying to bypass things such as account creation limits.

Although I wrote those suggestions before even really testing the tool and when I did I couldn't get it to work as stated. It would still ask for email verification and when I would do that twitch would then say the browser I was using was not supported. Which I think happens because it knows the browser is in testing mode or whatever it is called. Which could possibly be fixed by using fake-useragent.

Have you tried the tool recently? I'm not sure it still works.

I do still need to make a bunch of accounts but am currently finishing up on a chatbot project. Maybe once that is done I will try to get an account creation tool working or improving on this one.

**Comment by Necrownyx** [comment]
I have not tested the project recently as twitch constantly updates their website to stop programs like this from working unless something has changed recently the program is simple to fix yourself.

i'm going to close this issue as unplanned and i will come back and implement the changes suggested at a later date
