### ISSUE TITLE
"invalid webbrowser" error after entering dob

### ISSUE THREAD

**Issue by vanity3k** [Necrownyx/Twitch-Account-Toolbox#5]
if you could add me on discord that would be great "bDES7X6-gSF6EgTmm6_25WvfX!?q_wGm#7685"

my question was: i recently made my own similar thing as this and whenever it gets to the enter birthday page and enters all the information and then clicks continue the website gives a error such as "invalid webbrowser" ive tried chrome driver and geckodriver

**Comment by Necrownyx** [comment]
I don't really add people on discord other than friends sorry,

I am going to start working on this project again very soon so if I encounter this error I will see if I can find a solution,

In a closed issue on this project a Python package called fake-useragent is mentioned, this might fix the issue

Nyx,

**Comment by vanity3k** [comment]
i will see what i can do with fake-useragent

**Comment by vanity3k** [comment]
still seems to have not works for me this is the code ive used for it


while True:
    ua = UserAgent()
    user_agent = ua.random
    print(f"Using user agent: {user_agent}")

    service = Service(executable_path='./PATH/geckodriver.exe')
    driver = webdriver.Firefox(service=service, desired_capabilities={"general.userAgent": user_agent})
    driver.get("https://www.twitch.tv/")

**Comment by Necrownyx** [comment]
I also tried fake-useragent without luck recently,

I have found a project that I believe is called undetected chrome driver that may solve our problem.

**Comment by vanity3k** [comment]
i just tried undetected chrome driver as well and that didnt work for me
